In [3]:
import os
import torch  # 引入Pytorch库
print(torch.cuda.is_available())  # 测试GPU是否可用,为True则表示GPU可用
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # 指定程序在第一块GPU上运行


True


In [4]:
import torch
from torch.autograd import Variable
a = torch.FloatTensor([4])  # 定义张量a
print(Variable(a))  # 把张量a转化为Variable对象，输出:tensor([4.])
# 把张量a转化为支持梯度计算的Variable对象，输出:tensor([4.], requires_grad=True)
print(Variable(a, requires_grad=True))
print(a.data)  # Variable对象转化为张量，输出:tensor([4.])


tensor([4.])
tensor([4.], requires_grad=True)
tensor([4.])


In [10]:
import torch
x = torch.ones(2, 2, requires_grad=True)  # 定义一个Variable对象，并且打开梯度计算
m = x + 2  # 通过计算得到了m变量
f = m.mean()  # 通过m的mean()方法，得到了一个标量
f.backward()  # 调用标量的backward()进行自动求导
print(f, x.grad)

tensor(3., grad_fn=<MeanBackward0>) tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
